### PR TITLE
wip: generate ssh private key on the fly, and pass it to worker

### PR DESCRIPTION
**Pull request by igorwwwwwwwwwwwwwwwwwwww**
refs travis-ci/reliability#195, https://github.com/travis-ci/reliability/issues/202

### CODE REVIEW

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
This has not actually been tested yet. We'll also need to implement the client side at https://github.com/travis-ci/worker/pull/519.

**Review by ryndaniels — APPROVED** [review]
:shipit:

**Comment by bogdanap** [comment]
✅ Tested on staging, in combination with https://github.com/travis-ci/worker/pull/523

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Yay! (I can't approve my own PR)

**Pull request merged**
